// GENERATED by tools/build_atlas.py — do not edit by hand.
//
// Slot rects into assets/atlas.png, packed from three Kenney CC0 packs (see
// assets/CREDITS.md). Change the art by editing the MANIFEST in the packer and re-running
// it; nothing in the renderer hard-codes a sprite position.
#pragma once

#include <cstdint>

namespace mmo {

inline constexpr int kAtlasTile = 16;
// Each terrain has this many textured variants, packed consecutively as
// kTerrainX, kTerrainX1, kTerrainX2 — a single repeated motif tiles visibly.
inline constexpr int kTerrainVariants = 3;

struct AtlasRect {
    std::int16_t x;
    std::int16_t y;
};

enum class Slot : std::uint8_t {
    kTerrainGrass,
    kTerrainGrass1,
    kTerrainGrass2,
    kTerrainDirt,
    kTerrainDirt1,
    kTerrainDirt2,
    kTerrainWater,
    kTerrainWater1,
    kTerrainWater2,
    kTerrainStone,
    kTerrainStone1,
    kTerrainStone2,
    kTerrainSand,
    kTerrainSand1,
    kTerrainSand2,
    kTerrainSnow,
    kTerrainSnow1,
    kTerrainSnow2,
    kTerrainMarsh,
    kTerrainMarsh1,
    kTerrainMarsh2,
    kTerrainAsh,
    kTerrainAsh1,
    kTerrainAsh2,
    kTerrainPath,
    kTerrainPath1,
    kTerrainPath2,
    kTerrainBuilding,
    kTerrainBuilding1,
    kTerrainBuilding2,
    kCropSeedling,
    kCropGrowing,
    kCropWheatRipe,
    kCropCarrotRipe,
    kCropPumpkinRipe,
    kBuildHearth,
    kBuildPlot,
    kCount,
};

inline constexpr AtlasRect kAtlasRects[static_cast<int>(Slot::kCount)] = {
    {1, 1},  // kTerrainGrass
    {19, 1},  // kTerrainGrass1
    {37, 1},  // kTerrainGrass2
    {55, 1},  // kTerrainDirt
    {73, 1},  // kTerrainDirt1
    {91, 1},  // kTerrainDirt2
    {109, 1},  // kTerrainWater
    {127, 1},  // kTerrainWater1
    {1, 19},  // kTerrainWater2
    {19, 19},  // kTerrainStone
    {37, 19},  // kTerrainStone1
    {55, 19},  // kTerrainStone2
    {73, 19},  // kTerrainSand
    {91, 19},  // kTerrainSand1
    {109, 19},  // kTerrainSand2
    {127, 19},  // kTerrainSnow
    {1, 37},  // kTerrainSnow1
    {19, 37},  // kTerrainSnow2
    {37, 37},  // kTerrainMarsh
    {55, 37},  // kTerrainMarsh1
    {73, 37},  // kTerrainMarsh2
    {91, 37},  // kTerrainAsh
    {109, 37},  // kTerrainAsh1
    {127, 37},  // kTerrainAsh2
    {1, 55},  // kTerrainPath
    {19, 55},  // kTerrainPath1
    {37, 55},  // kTerrainPath2
    {55, 55},  // kTerrainBuilding
    {73, 55},  // kTerrainBuilding1
    {91, 55},  // kTerrainBuilding2
    {109, 55},  // kCropSeedling
    {127, 55},  // kCropGrowing
    {1, 73},  // kCropWheatRipe
    {19, 73},  // kCropCarrotRipe
    {37, 73},  // kCropPumpkinRipe
    {55, 73},  // kBuildHearth
    {73, 73},  // kBuildPlot
};

[[nodiscard]] inline constexpr AtlasRect rect_of(Slot s) noexcept {
    return kAtlasRects[static_cast<int>(s)];
}

// --- Animation sheets ----------------------------------------------------------------
// Ninja Adventure walk sheets are COLUMN = facing, ROW = frame. Verified by rendering the
// grid with labels; do not reorder these without re-checking the art.
enum : int { kDirDown = 0, kDirUp = 1, kDirLeft = 2, kDirRight = 3, kDirCount = 4 };

struct AtlasAnim {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t cols;  // facings
    std::uint8_t rows;  // frames
};

enum class Anim : std::uint8_t {
    kPlayer,
    kMobSlime,
    kMobSpider,
    kMobSpirit,
    kChicken,
    kCow,
    kCount,
};

inline constexpr AtlasAnim kAtlasAnims[static_cast<int>(Anim::kCount)] = {
    {1, 91, 4, 4},  // kPlayer
    {1, 163, 4, 4},  // kMobSlime
    {1, 235, 4, 4},  // kMobSpider
    {1, 307, 4, 4},  // kMobSpirit
    {1, 379, 2, 1},  // kChicken
    {1, 397, 2, 1},  // kCow
};

[[nodiscard]] inline constexpr const AtlasAnim& anim_of(Anim a) noexcept {
    return kAtlasAnims[static_cast<int>(a)];
}

// `dir` and `frame` are wrapped, so a caller may pass a free-running frame counter and a
// facing that this particular sheet does not have (animals only face two ways).
[[nodiscard]] inline constexpr AtlasRect anim_frame(Anim a, int dir, int frame) noexcept {
    const AtlasAnim& s = anim_of(a);
    const int c = (dir % s.cols + s.cols) % s.cols;
    const int r = (frame % s.rows + s.rows) % s.rows;
    return AtlasRect{static_cast<std::int16_t>(s.x + c * (kAtlasTile + 2)),
                     static_cast<std::int16_t>(s.y + r * (kAtlasTile + 2))};
}

// --- Multi-tile sprites --------------------------------------------------------------
// Drawn as ONE quad spanning `w` x `h` tiles, anchored so the bottom-centre sits on the
// owning tile — a tree's trunk is on its tile and the canopy overhangs the ones above.
struct AtlasBig {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t w;  // tiles wide
    std::uint8_t h;  // tiles tall
};

enum class Big : std::uint8_t {
    kTreeBroad,
    kTreePine,
    kHouseOrange,
    kHouseCream,
    kHouseAmber,
    kHouseRed,
    kHouseBlue,
    kHouseTan,
    kHouseWood,
    kHutSnowA,
    kHutSnowB,
    kHutSnowC,
    kRuinA,
    kRuinB,
    kTentA,
    kTentB,
    kTentC,
    kCount,
};

inline constexpr AtlasBig kAtlasBigs[static_cast<int>(Big::kCount)] = {
    {1, 415, 2, 3},  // kTreeBroad
    {1, 465, 2, 3},  // kTreePine
    {1, 515, 4, 3},  // kHouseOrange
    {1, 565, 4, 3},  // kHouseCream
    {1, 615, 4, 3},  // kHouseAmber
    {1, 665, 4, 3},  // kHouseRed
    {1, 715, 3, 3},  // kHouseBlue
    {1, 765, 3, 3},  // kHouseTan
    {1, 815, 3, 3},  // kHouseWood
    {1, 865, 3, 3},  // kHutSnowA
    {1, 915, 3, 3},  // kHutSnowB
    {1, 965, 3, 3},  // kHutSnowC
    {1, 1015, 3, 3},  // kRuinA
    {1, 1065, 3, 3},  // kRuinB
    {1, 1115, 3, 3},  // kTentA
    {1, 1165, 3, 3},  // kTentB
    {1, 1215, 3, 3},  // kTentC
};

[[nodiscard]] inline constexpr const AtlasBig& big_of(Big b) noexcept {
    return kAtlasBigs[static_cast<int>(b)];
}

// --- Particle strips -----------------------------------------------------------------
// Ambience sprites, off the tile grid: a leaf is 12x7, a raindrop 8x8. Frames run left to
// right in one strip.
struct AtlasFx {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t w;
    std::uint8_t h;
    std::uint8_t frames;
};

enum class Fx : std::uint8_t {
    kLeaf,
    kLeafPink,
    kRain,
    kSnow,
    kCount,
};

inline constexpr AtlasFx kAtlasFx[static_cast<int>(Fx::kCount)] = {
    {1, 1265, 12, 7, 6},  // kLeaf
    {1, 1274, 12, 7, 6},  // kLeafPink
    {1, 1283, 8, 8, 3},  // kRain
    {1, 1293, 8, 8, 7},  // kSnow
};

[[nodiscard]] inline constexpr const AtlasFx& fx_of(Fx f) noexcept {
    return kAtlasFx[static_cast<int>(f)];
}

// `frame` is wrapped, so a caller may pass a free-running counter.
[[nodiscard]] inline constexpr AtlasRect fx_frame(Fx f, int frame) noexcept {
    const AtlasFx& s = fx_of(f);
    const int i = (frame % s.frames + s.frames) % s.frames;
    return AtlasRect{static_cast<std::int16_t>(s.x + i * (s.w + 2)), s.y};
}

}  // namespace mmo
