// GENERATED by tools/build_atlas.py — do not edit by hand.
//
// Slot rects into assets/atlas.png, packed from three Kenney CC0 packs (see
// assets/CREDITS.md). Change the art by editing the MANIFEST in the packer and re-running
// it; nothing in the renderer hard-codes a sprite position.
#pragma once

#include <cstdint>

namespace mmo {

inline constexpr int kAtlasTile = 16;
// Each terrain has this many textured variants, packed consecutively as
// kTerrainX, kTerrainX1, kTerrainX2 — a single repeated motif tiles visibly.
inline constexpr int kTerrainVariants = 3;

struct AtlasRect {
    std::int16_t x;
    std::int16_t y;
};

enum class Slot : std::uint8_t {
    kTerrainGrass,
    kTerrainGrass1,
    kTerrainGrass2,
    kTerrainDirt,
    kTerrainDirt1,
    kTerrainDirt2,
    kTerrainWater,
    kTerrainWater1,
    kTerrainWater2,
    kTerrainStone,
    kTerrainStone1,
    kTerrainStone2,
    kTerrainSand,
    kTerrainSand1,
    kTerrainSand2,
    kTerrainSnow,
    kTerrainSnow1,
    kTerrainSnow2,
    kTerrainMarsh,
    kTerrainMarsh1,
    kTerrainMarsh2,
    kTerrainAsh,
    kTerrainAsh1,
    kTerrainAsh2,
    kTerrainPath,
    kTerrainPath1,
    kTerrainPath2,
    kTerrainBuilding,
    kTerrainBuilding1,
    kTerrainBuilding2,
    kCropSeedling,
    kCropGrowing,
    kCropWheatRipe,
    kCropCarrotRipe,
    kCropPumpkinRipe,
    kBuildHearth,
    kBuildPlot,
    kCount,
};

inline constexpr AtlasRect kAtlasRects[static_cast<int>(Slot::kCount)] = {
    {1, 1},  // kTerrainGrass
    {19, 1},  // kTerrainGrass1
    {37, 1},  // kTerrainGrass2
    {55, 1},  // kTerrainDirt
    {73, 1},  // kTerrainDirt1
    {91, 1},  // kTerrainDirt2
    {109, 1},  // kTerrainWater
    {127, 1},  // kTerrainWater1
    {1, 19},  // kTerrainWater2
    {19, 19},  // kTerrainStone
    {37, 19},  // kTerrainStone1
    {55, 19},  // kTerrainStone2
    {73, 19},  // kTerrainSand
    {91, 19},  // kTerrainSand1
    {109, 19},  // kTerrainSand2
    {127, 19},  // kTerrainSnow
    {1, 37},  // kTerrainSnow1
    {19, 37},  // kTerrainSnow2
    {37, 37},  // kTerrainMarsh
    {55, 37},  // kTerrainMarsh1
    {73, 37},  // kTerrainMarsh2
    {91, 37},  // kTerrainAsh
    {109, 37},  // kTerrainAsh1
    {127, 37},  // kTerrainAsh2
    {1, 55},  // kTerrainPath
    {19, 55},  // kTerrainPath1
    {37, 55},  // kTerrainPath2
    {55, 55},  // kTerrainBuilding
    {73, 55},  // kTerrainBuilding1
    {91, 55},  // kTerrainBuilding2
    {109, 55},  // kCropSeedling
    {127, 55},  // kCropGrowing
    {1, 73},  // kCropWheatRipe
    {19, 73},  // kCropCarrotRipe
    {37, 73},  // kCropPumpkinRipe
    {55, 73},  // kBuildHearth
    {73, 73},  // kBuildPlot
};

[[nodiscard]] inline constexpr AtlasRect rect_of(Slot s) noexcept {
    return kAtlasRects[static_cast<int>(s)];
}

// --- Animation sheets ----------------------------------------------------------------
// Ninja Adventure walk sheets are COLUMN = facing, ROW = frame. Verified by rendering the
// grid with labels; do not reorder these without re-checking the art.
enum : int { kDirDown = 0, kDirUp = 1, kDirLeft = 2, kDirRight = 3, kDirCount = 4 };

struct AtlasAnim {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t cols;  // facings
    std::uint8_t rows;  // frames
};

enum class Anim : std::uint8_t {
    kPlayer,
    kPlayerAttack,
    kMobSlime,
    kMobSpider,
    kMobSpirit,
    kMobSkull,
    kBoar,
    kWolf,
    kBear,
    kRacoon,
    kChicken,
    kCow,
    kHorse,
    kCount,
};

inline constexpr AtlasAnim kAtlasAnims[static_cast<int>(Anim::kCount)] = {
    {1, 91, 4, 4},  // kPlayer
    {1, 163, 4, 1},  // kPlayerAttack
    {1, 181, 4, 4},  // kMobSlime
    {1, 253, 4, 4},  // kMobSpider
    {1, 325, 4, 4},  // kMobSpirit
    {1, 397, 4, 4},  // kMobSkull
    {1, 469, 2, 1},  // kBoar
    {1, 487, 2, 1},  // kWolf
    {1, 505, 4, 4},  // kBear
    {1, 577, 4, 4},  // kRacoon
    {1, 649, 2, 1},  // kChicken
    {1, 667, 2, 1},  // kCow
    {1, 685, 2, 1},  // kHorse
};

[[nodiscard]] inline constexpr const AtlasAnim& anim_of(Anim a) noexcept {
    return kAtlasAnims[static_cast<int>(a)];
}

// `dir` and `frame` are wrapped, so a caller may pass a free-running frame counter and a
// facing that this particular sheet does not have (animals only face two ways).
[[nodiscard]] inline constexpr AtlasRect anim_frame(Anim a, int dir, int frame) noexcept {
    const AtlasAnim& s = anim_of(a);
    const int c = (dir % s.cols + s.cols) % s.cols;
    const int r = (frame % s.rows + s.rows) % s.rows;
    return AtlasRect{static_cast<std::int16_t>(s.x + c * (kAtlasTile + 2)),
                     static_cast<std::int16_t>(s.y + r * (kAtlasTile + 2))};
}

// --- Multi-tile sprites --------------------------------------------------------------
// Drawn as ONE quad spanning `w` x `h` tiles, anchored so the bottom-centre sits on the
// owning tile — a tree's trunk is on its tile and the canopy overhangs the ones above.
struct AtlasBig {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t w;  // tiles wide
    std::uint8_t h;  // tiles tall
};

enum class Big : std::uint8_t {
    kTreeBroad,
    kTreePine,
    kRoom,
    kHouseOrange,
    kHouseCream,
    kHouseAmber,
    kHouseRed,
    kHouseBlue,
    kHouseTan,
    kHouseWood,
    kHutSnowA,
    kHutSnowB,
    kHutSnowC,
    kRuinA,
    kRuinB,
    kTentA,
    kTentB,
    kTentC,
    kLogPost,
    kRampart,
    kGate,
    kStakeA,
    kStakeB,
    kStakeC,
    kCount,
};

inline constexpr AtlasBig kAtlasBigs[static_cast<int>(Big::kCount)] = {
    {1, 703, 4, 3},  // kTreeBroad
    {1, 753, 4, 3},  // kTreePine
    {1, 803, 12, 9},  // kRoom
    {1, 949, 4, 3},  // kHouseOrange
    {1, 999, 4, 3},  // kHouseCream
    {1, 1049, 4, 3},  // kHouseAmber
    {1, 1099, 4, 3},  // kHouseRed
    {1, 1149, 3, 3},  // kHouseBlue
    {1, 1199, 3, 3},  // kHouseTan
    {1, 1249, 3, 3},  // kHouseWood
    {1, 1299, 3, 3},  // kHutSnowA
    {1, 1349, 3, 3},  // kHutSnowB
    {1, 1399, 3, 3},  // kHutSnowC
    {1, 1449, 3, 3},  // kRuinA
    {1, 1499, 3, 3},  // kRuinB
    {1, 1549, 3, 3},  // kTentA
    {1, 1599, 3, 3},  // kTentB
    {1, 1649, 3, 3},  // kTentC
    {1, 1699, 3, 5},  // kLogPost
    {1, 1781, 3, 3},  // kRampart
    {1, 1831, 3, 3},  // kGate
    {1, 1881, 1, 2},  // kStakeA
    {1, 1915, 1, 2},  // kStakeB
    {1, 1949, 1, 2},  // kStakeC
};

[[nodiscard]] inline constexpr const AtlasBig& big_of(Big b) noexcept {
    return kAtlasBigs[static_cast<int>(b)];
}

// --- Particle strips -----------------------------------------------------------------
// Ambience sprites, off the tile grid: a leaf is 12x7, a raindrop 8x8. Frames run left to
// right in one strip.
struct AtlasFx {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t w;
    std::uint8_t h;
    std::uint8_t frames;
};

enum class Fx : std::uint8_t {
    kLeaf,
    kLeafPink,
    kRain,
    kSnow,
    kArrow,
    kSlash,
    kFire,
    kIce,
    kEarth,
    kShock,
    kBlast,
    kShield,
    kAura,
    kBoost,
    kSparkFx,
    kCircle,
    kSlashHeavy,
    kSlashCombo,
    kKunai,
    kShuriken,
    kFireball,
    kEnergyBall,
    kSmoke,
    kFacePlayer,
    kCount,
};

inline constexpr AtlasFx kAtlasFx[static_cast<int>(Fx::kCount)] = {
    {1, 1983, 12, 7, 6},  // kLeaf
    {1, 1992, 12, 7, 6},  // kLeafPink
    {1, 2001, 8, 8, 3},  // kRain
    {1, 2011, 8, 8, 7},  // kSnow
    {1, 2021, 16, 16, 1},  // kArrow
    {1, 2039, 32, 32, 4},  // kSlash
    {1, 2073, 25, 30, 8},  // kFire
    {1, 2105, 32, 32, 10},  // kIce
    {1, 2139, 30, 30, 14},  // kEarth
    {1, 2171, 20, 28, 8},  // kShock
    {1, 2201, 40, 40, 9},  // kBlast
    {1, 2243, 24, 26, 6},  // kShield
    {1, 2271, 25, 24, 5},  // kAura
    {1, 2297, 53, 35, 8},  // kBoost
    {1, 2334, 27, 35, 10},  // kSparkFx
    {1, 2371, 32, 32, 4},  // kCircle
    {1, 2405, 32, 32, 4},  // kSlashHeavy
    {1, 2439, 32, 32, 4},  // kSlashCombo
    {1, 2473, 65, 59, 10},  // kKunai
    {1, 2534, 69, 54, 10},  // kShuriken
    {1, 2590, 16, 16, 4},  // kFireball
    {1, 2608, 16, 16, 4},  // kEnergyBall
    {1, 2626, 32, 32, 6},  // kSmoke
    {1, 2660, 38, 38, 1},  // kFacePlayer
};

[[nodiscard]] inline constexpr const AtlasFx& fx_of(Fx f) noexcept {
    return kAtlasFx[static_cast<int>(f)];
}

// `frame` is wrapped, so a caller may pass a free-running counter.
[[nodiscard]] inline constexpr AtlasRect fx_frame(Fx f, int frame) noexcept {
    const AtlasFx& s = fx_of(f);
    const int i = (frame % s.frames + s.frames) % s.frames;
    return AtlasRect{static_cast<std::int16_t>(s.x + i * (s.w + 2)), s.y};
}

// --- Ability icons -------------------------------------------------------------------
// The two-slot ability HUD's icons, 24x24, each with its greyed twin packed one cell to the
// right so `icon_rect(icon, disabled)` is a single offset. Off the tile grid, like the FX
// strips. The enum is in AbilityId order, so an ability maps to its icon by a plain cast.
// Picks (looked at, not guessed): WhirlCleave=Spell/Cut — a sweeping slash reads as a
// spinning cleave where a fist (Punch) reads as a jab; CrushBlow=Spell/AttackUpgrade — a
// charged weapon with impact sparkles for the heavy finisher; FanVolley=Arrow; SmokeBomb=
// Spell/Mist; ElementalNova=Spell/Explosion; RainCall=Meteo/Rain.
struct AtlasIcon {
    std::int16_t x;
    std::int16_t y;
};

inline constexpr int kIconPx = 24;

enum class Icon : std::uint8_t {
    kWhirlCleave,
    kCrushBlow,
    kFanVolley,
    kSmokeBomb,
    kElementalNova,
    kRainCall,
    kCount,
};

inline constexpr AtlasIcon kAtlasIcons[static_cast<int>(Icon::kCount)] = {
    {1, 2700},  // kWhirlCleave (lit at x; disabled at x + kIconPx + 2)
    {1, 2726},  // kCrushBlow (lit at x; disabled at x + kIconPx + 2)
    {1, 2752},  // kFanVolley (lit at x; disabled at x + kIconPx + 2)
    {1, 2778},  // kSmokeBomb (lit at x; disabled at x + kIconPx + 2)
    {1, 2804},  // kElementalNova (lit at x; disabled at x + kIconPx + 2)
    {1, 2830},  // kRainCall (lit at x; disabled at x + kIconPx + 2)
};

// `disabled` picks the greyed twin, packed one cell to the right of the lit icon.
[[nodiscard]] inline constexpr AtlasRect icon_rect(Icon i, bool disabled) noexcept {
    const AtlasIcon& s = kAtlasIcons[static_cast<int>(i)];
    return AtlasRect{static_cast<std::int16_t>(s.x + (disabled ? 1 : 0) * (kIconPx + 2)),
                     s.y};
}

// --- Terrain edge sets ---------------------------------------------------------------
// One EDGE set per terrain (see EDGE_MANIFEST in the packer). Where two terrains meet, the
// tile is filled with the lower-priority one and the higher-priority terrain's edge tile is
// laid over it — so this is 11 sets rather than the 55 a per-pair scheme would need, and it
// covers pairs the pack draws no art for.
//
// The mask is Godot 3's BITMASK_3X3_MINIMAL, because four of these sets ARE the pack's own
// autotiles and that is what they were drawn against. A corner bit counts only when both
// adjacent sides are set; `edge_mask` below is the only place that rule is written, and it
// mirrors `minimal_mask` in the packer.
inline constexpr int kTransMasks = 47;
inline constexpr int kTransTerrains = 11;

inline constexpr int kEdgeTL = 1, kEdgeT = 2, kEdgeTR = 4;
inline constexpr int kEdgeL = 8, kEdgeC = 16, kEdgeR = 32;
inline constexpr int kEdgeBL = 64, kEdgeB = 128, kEdgeBR = 256;

// Every mask the minimal rule can produce is drawn, so the plain fill is the only case a
// caller has to branch on.
inline constexpr int kEdgeFull = 511;

inline constexpr AtlasRect kAtlasTrans[kTransTerrains] = {
    {1, 2856},  // Grass — generated
    {1, 2874},  // Dirt — TilesetFloor.png#2
    {1, 2892},  // Water — TilesetWater.png#18
    {1, 2910},  // Stone — generated
    {1, 2928},  // Sand — generated
    {1, 2946},  // Tree — generated
    {1, 2964},  // Snow — TilesetSnow.png#17
    {1, 2982},  // Marsh — generated
    {1, 3000},  // Ash — generated
    {1, 3018},  // Path — generated
    {1, 3036},  // Building — generated
};

// Whether this terrain's variant 0 is a genuinely PLAIN fill, derived from the manifest by
// comparing it against variant 1 rather than restated by hand. Two terrains are false:
// Ninja Adventure ships no flat ash and no bare rock, so stone and ash use a whole-tile
// masonry motif for all three variants. The renderer needs to know, because an unmirrored
// whole-tile motif tiles into a perfect brick lattice — see `ground` in raylib_bridge.cpp.
inline constexpr bool kTerrainHasPlain[kTransTerrains] = {
    true,  // Grass
    true,  // Dirt
    true,  // Water
    false,  // Stone
    true,  // Sand
    true,  // Tree
    true,  // Snow
    true,  // Marsh
    false,  // Ash
    true,  // Path
    true,  // Building
};

// Column of each mask in a row. Only 47 of the 512 nine-bit values are reachable through
// the minimal rule; the rest are -1 and a caller that lands on one has built its mask by
// some other rule than `edge_mask`.
inline constexpr std::int8_t kEdgeSlot[512] = {
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    0, -1, 1, -1, -1, -1, -1, -1, 2, -1, 3, 4, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    5, -1, 6, -1, -1, -1, 7, -1, 8, -1, 9, 10, -1, -1, 11, 12,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    13, -1, 14, -1, -1, -1, -1, -1, 15, -1, 16, 17, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    18, -1, 19, -1, -1, -1, 20, -1, 21, -1, 22, 23, -1, -1, 24, 25,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, 26, -1, 27, 28, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, 29, -1, 30, 31, -1, -1, 32, 33,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    34, -1, 35, -1, -1, -1, 36, -1, 37, -1, 38, 39, -1, -1, 40, 41,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, 42, -1, 43, 44, -1, -1, 45, 46,
};

// Godot's BITMASK_3X3_MINIMAL. `n` answers "does the neighbour at (dx, dy) count as this
// terrain"; a corner counts only when both of its adjacent sides do.
template <typename Neighbour>
[[nodiscard]] inline constexpr int edge_mask(Neighbour n) noexcept {
    const bool t = n(0, -1), b = n(0, 1), l = n(-1, 0), r = n(1, 0);
    int m = kEdgeC;
    if (t) m |= kEdgeT;
    if (b) m |= kEdgeB;
    if (l) m |= kEdgeL;
    if (r) m |= kEdgeR;
    if (t && l && n(-1, -1)) m |= kEdgeTL;
    if (t && r && n(1, -1)) m |= kEdgeTR;
    if (b && l && n(-1, 1)) m |= kEdgeBL;
    if (b && r && n(1, 1)) m |= kEdgeBR;
    return m;
}

// `mask` must be one `edge_mask` can return; kEdgeFull is the plain fill and has a tile too.
[[nodiscard]] inline constexpr AtlasRect trans_rect(int terrain, int mask) noexcept {
    const AtlasRect& row = kAtlasTrans[terrain];
    const int slot = kEdgeSlot[mask & 0x1FF];
    return AtlasRect{static_cast<std::int16_t>(row.x + slot * (kAtlasTile + 2)), row.y};
}
// --- Deluxe player rig (32px animated) -----------------------------------------------
// The player's own high-detail rig: 32px frames (a 16px body centred with overflow room so
// a swing reaches past its tile). Same COLUMN = facing, ROW = frame convention as the 16px
// sheets, verified by pixel-matching against the pack's master sheet. Bodies come first,
// then the frame-aligned katana overlays (blade + baked swoosh); empty overlay cells draw
// nothing. The renderer composites e.g. kKatanaAttack over kAttack per (facing, frame).
inline constexpr int kDeluxeTile = 32;

struct AtlasDeluxe {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t cols;  // facings
    std::uint8_t rows;  // frames
};

enum class Deluxe : std::uint8_t {
    kIdle,
    kWalk,
    kAttack,
    kHit,
    kKatanaIdle,
    kKatanaAttack,
    kKatanaWalk,
    kKatanaHit,
    kCount,
};

inline constexpr AtlasDeluxe kAtlasDeluxe[static_cast<int>(Deluxe::kCount)] = {
    {1, 5250, 4, 4},  // kIdle
    {1, 5386, 4, 4},  // kWalk
    {1, 5522, 4, 4},  // kAttack
    {1, 5658, 4, 2},  // kHit
    {1, 5726, 4, 4},  // kKatanaIdle
    {1, 5862, 4, 4},  // kKatanaAttack
    {1, 5998, 4, 4},  // kKatanaWalk
    {1, 6134, 4, 2},  // kKatanaHit
};

[[nodiscard]] inline constexpr const AtlasDeluxe& deluxe_of(Deluxe d) noexcept {
    return kAtlasDeluxe[static_cast<int>(d)];
}

// `dir` and `frame` are wrapped, so a caller may pass a free-running counter and a facing
// the sheet has. A one-row sheet (none here yet) would be driven by `frame` as the anims are.
[[nodiscard]] inline constexpr AtlasRect deluxe_frame(Deluxe d, int dir, int frame) noexcept {
    const AtlasDeluxe& s = deluxe_of(d);
    const int c = (dir % s.cols + s.cols) % s.cols;
    const int r = (frame % s.rows + s.rows) % s.rows;
    return AtlasRect{static_cast<std::int16_t>(s.x + c * (kDeluxeTile + 2)),
                     static_cast<std::int16_t>(s.y + r * (kDeluxeTile + 2))};
}

// The katana the ninja carries on its back when not swinging: a single 6x10 sprite the
// renderer draws offset and rotated to the facing (the pack's own weapon.gd rule).
struct AtlasSprite {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t w;
    std::uint8_t h;
};

inline constexpr AtlasSprite kKatanaCarry = {1, 6202, 6, 10};

// --- The boss: Giant Red Samurai (F3) ------------------------------------------------
// One entry per POSE strip (Idle/Walk/AttackLeft/AttackRight/ChargeLeft/ChargeRight/Hit) plus
// the 38x38 Faceset for the HP-bar icon. Off the tile grid and NOT square, like AtlasFx: each
// pose is a horizontal strip of `frames` cells of `w` x `h` (the giant is ~4 tiles across).
// `foot` is the ground line -- the row (from the cell top) where the boss's feet sit -- so the
// renderer anchors it feet-down whether the cell is 48px (idle/walk/hit) or 96px (attack/
// charge) tall. Left/Right poses are separate sheets, chosen by the boss's facing.
struct AtlasBoss {
    std::int16_t x;
    std::int16_t y;
    std::uint8_t w;
    std::uint8_t h;
    std::uint8_t frames;
    std::uint8_t foot;  // ground-line row from the cell top, for feet-anchored drawing
};

enum class Boss : std::uint8_t {
    kIdle,
    kWalk,
    kAttackLeft,
    kAttackRight,
    kChargeLeft,
    kChargeRight,
    kHit,
    kFace,
    kCount,
};

inline constexpr AtlasBoss kAtlasBoss[static_cast<int>(Boss::kCount)] = {
    {1, 6214, 96, 48, 6, 44},  // kIdle
    {1, 6264, 96, 48, 6, 48},  // kWalk
    {1, 6314, 96, 96, 4, 83},  // kAttackLeft
    {1, 6412, 96, 96, 4, 83},  // kAttackRight
    {1, 6510, 96, 96, 3, 78},  // kChargeLeft
    {1, 6608, 96, 96, 3, 78},  // kChargeRight
    {1, 6706, 96, 48, 4, 46},  // kHit
    {1, 6756, 38, 38, 1, 38},  // kFace
};

[[nodiscard]] inline constexpr const AtlasBoss& boss_of(Boss b) noexcept {
    return kAtlasBoss[static_cast<int>(b)];
}

// `frame` is wrapped, so a caller may pass a free-running counter.
[[nodiscard]] inline constexpr AtlasRect boss_frame(Boss b, int frame) noexcept {
    const AtlasBoss& s = boss_of(b);
    const int i = (frame % s.frames + s.frames) % s.frames;
    return AtlasRect{static_cast<std::int16_t>(s.x + i * (s.w + 2)), s.y};
}

}  // namespace mmo
