// GENERATED by tools/build_combat_pack.py from data/combat/**.json — do not hand-edit.
// Re-run the packer after changing any authored document; this file and
// assets/_gen/combat_pack.json are regenerated together and must be committed together.
#pragma once

#include <cstdint>

namespace mmo {

inline constexpr int kCombatPackSchemaMajor = 1;
inline constexpr int kCombatPackSchemaMinor = 0;
inline constexpr const char* kCombatPackStructHash = "1d85a6caef391f5e66111504da45f787add1988f03e60d58093b79fe744e1016";
inline constexpr const char* kCombatPackFullHash = "ecfcd91fe3ea58cd921ddda788fb44c91377c6c217c34b588f6509035d64db00";

namespace combat_ids {

inline constexpr std::uint16_t kEntityMeteorBody = 1;
inline constexpr std::uint16_t kEntityRockSpike = 2;
inline constexpr std::uint16_t kFxGroundCrack = 1;
inline constexpr std::uint16_t kFxRockBlast = 2;
inline constexpr std::uint16_t kFxRockBreak = 3;
inline constexpr std::uint16_t kFxRockCrumble = 4;
inline constexpr std::uint16_t kFxRockFallHot = 5;
inline constexpr std::uint16_t kFxRockSpikeIdle = 6;
inline constexpr std::uint16_t kFxRockSpikeRise = 7;
inline constexpr std::uint16_t kFxTelegraphRingRock = 8;
inline constexpr std::uint16_t kIconBookRock = 1;
inline constexpr std::uint16_t kSkillMeteor = 1;
inline constexpr std::uint16_t kSkillSpike = 2;
inline constexpr std::uint16_t kSndCast = 1;
inline constexpr std::uint16_t kSndCastHeavy = 2;
inline constexpr std::uint16_t kSndExplosionHeavy = 3;
inline constexpr std::uint16_t kSndMeteorWhoosh = 4;
inline constexpr std::uint16_t kSndRockBreak = 5;
inline constexpr std::uint16_t kStatusCold = 1;
inline constexpr std::uint16_t kStatusEarth = 2;
inline constexpr std::uint16_t kStatusHeat = 3;
inline constexpr std::uint16_t kStatusShock = 4;
inline constexpr std::uint16_t kStatusStagger = 5;
inline constexpr std::uint16_t kStatusWet = 6;

}  // namespace combat_ids

}  // namespace mmo
